### ISSUE TITLE
10.0.2.0/24 OR 10.0.2.0/24?

### ISSUE THREAD

**Issue by wizardnet972** [kovarus/aws-cli-create-vpcs#3]
In docs configuration is `SUBNET_PRIVATE_CIDR="10.0.2.0/24"`, but in https://docs.aws.amazon.com/vpc/latest/userguide/vpc-subnets-commands-example.html

say `10.0.0.0/24`.

 `aws ec2 create-subnet --vpc-id vpc-2f09a348 --cidr-block 10.0.0.0/24`

So `10.0.2.0/24` is okay?

**Comment by JoeArauzo** [comment]
Yes. It’s okay. I simply chose a different network address. Still valid.
